spring.application.name=Backend-valkyrie
#ffmpeg.path=ffmpeg
ffmpeg.path=/usr/bin/ffmpeg

#spring.datasource.url=jdbc:mysql://mysql-crime:3306/crime_db
spring.datasource.url=jdbc:mysql://localhost:3306/crime_db

spring.datasource.username=crime_user
spring.datasource.password=crime_password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

aws.region=us-east-1
aws.s3.bucket.raw=teste-bucket-tcc1
aws.s3.bucket.trusted=teste-bucket-tcc1
aws.s3.bucket.client=teste-bucket-tcc1

# payload fixo como
# "imagem": imagem, # multipart do file
# "nomeArquivo": nomeArquivo # nome objeto S3
modelo.url=http://localhost:8080/file/teste
# caso aponte para o proprio back q nem acima http://localhost:8080/file/teste
modelo.mock=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB