services:
  video-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      FFMPEG_PATH: ffmpeg
      AWS_REGION: us-east-1
      AWS_S3_BUCKET_RAW: teste-bucket-tcc1
      AWS_S3_BUCKET_TRUSTED: teste-bucket-tcc1
      AWS_S3_BUCKET_CLIENT: teste-bucket-tcc1
      SPRING_DATASOURCE_URL: jdbc:mysql://crime-mysql:3306/crime_db
      SPRING_DATASOURCE_USERNAME: crime_user
      SPRING_DATASOURCE_PASSWORD: crime_password
      MODELO_URL: http://localhost:8080/file/teste
      MODELO_MOCK: true
      AWS_ACCESS_KEY_ID: ASIARHBDUCH7HVXJO56M
      AWS_SECRET_ACCESS_KEY: hNZhK3C/gtmgielb0cfWZA8jPJi7GvzyBije8Jmr
      AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjECIaCXVzLXdlc3QtMiJIMEYCIQCBNs7rdB4iv8by9iyghbviT6ziLOwTZ7vj/XEPhuHfvQIhAJgRobtm2n90LlIExvN4zhnbBwN+/8OXziWkQO01xSJPKr8CCOv//////////wEQARoMMDgzODI2NTc3OTE4IgxR/GpCb0N5bJTT2QwqkwKP1dVH7WjQIbrDpJQi6d1ZjkPj2PDdsCSijM+3cPX2ao6mbMUkP0HOA3I5ASj7K1838LQyabdCf3IxRyyVA5D9vAEY9m7nRvkO1w9Lp871mYDd9n1Xtmh3SfVBqD6ZdUZJtBS+l5Qv0rHyyEDYSutAkvqtCBZu3zaj7E5xK0V7Pu3ybEBCy6iGGmc+4P7ehYxiTnat78WT7mzAkg0oZ7Dx1NIYpfqB4Y3GJ7y+NuwFdEuvl/6NXETqUDyFikbZQYB+ilzVolt2WKQia9p664e5bFp5+hD5sPW2RZaBl3VgGj53lLkGQxI2h1xfGtEl9WfcDsEPrg5H9q8UAT+Pa+kPDXQ34qzDiyW6XdCNaxswVJ03OTCcnpHWBjqcASgloN9k8nMa0VB4fOvid+53OsVm+FF4HclTmedKqyY4xvBwGoM3ZGRNzeRGB6HmkkPb27svNcdrgZJ55Cm+snqTey5rTbD9oJzDmsLXTaIm1+ohD7e8vth+6HXTL5fwM0zQJeGjvTzxTyhVr1FSSd07ktq4AUEKPbMCXSrg8JsuUtSptfS1O9iXs7UoOEM/TQO+atcD3N/X1+U36Q==
    networks:
      - crime-network

networks:
  crime-network:
    external: true
